FROM golang:1.8.1-alpine

ENV SOURCES /go/src/learning/advanced-cloud-native-go-gin/Discovery/Kubernetes/
COPY . ${SOURCES}

RUN cd ${SOURCES}client/ && CGO_ENABLED=0 go build

WORKDIR ${SOURCES}client/
CMD ${SOURCES}client/client
